# Generated by Django 5.2.12 on 2026-03-17 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_role', models.CharField(choices=[('analyst', 'Аналитик'), ('developer', 'Разработчик'), ('tester', 'Тестировщик'), ('designer', 'Дизайнер'), ('researcher', 'Исследователь')], max_length=20, verbose_name='Желаемая роль')),
                ('assigned_role', models.CharField(blank=True, choices=[('analyst', 'Аналитик'), ('developer', 'Разработчик'), ('tester', 'Тестировщик'), ('designer', 'Дизайнер'), ('researcher', 'Исследователь')], max_length=20, null=True, verbose_name='Назначенная роль')),
                ('message', models.TextField(blank=True, verbose_name='Сопроводительное сообщение')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='projects.project', verbose_name='Проект')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кто рассмотрел')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на вступление',
                'verbose_name_plural': 'Заявки на вступление',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'project'), name='unique_pending_request_per_user_project')],
            },
        ),
    ]
