# Generated by Django 5.2.12 on 2026-03-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_joinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('done', 'Завершен')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
    ]
