# Generated by Django 5.2.12 on 2026-06-03 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectinvitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectInvitation',
        ),
    ]
