# Generated by Django 5.2.12 on 2026-03-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkpublication',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='vk_attachments/'),
        ),
        migrations.AddField(
            model_name='vkpublication',
            name='attachment_type',
            field=models.CharField(choices=[('none', 'Без вложения'), ('photo', 'Фото'), ('doc', 'Документ')], default='none', max_length=20, verbose_name='Тип вложения'),
        ),
        migrations.AddField(
            model_name='vkpublication',
            name='vk_attachment_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID вложения в VK'),
        ),
    ]
