# Generated by Django 5.2.13 on 2026-05-11 03:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_project_status'),
        ('tasks', '0004_task_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
                ('answers', models.JSONField(default=dict, verbose_name='Ответы')),
                ('status', models.CharField(choices=[('pending', 'Ожидает заполнения'), ('draft', 'Черновик'), ('submitted', 'Сдан на проверку'), ('reviewed', 'Проверен'), ('rejected', 'Отправлен на доработку')], default='pending', max_length=20, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата сдачи')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('review_comment', models.TextField(blank=True, verbose_name='Комментарий проверяющего')),
                ('tasks_data', models.JSONField(blank=True, default=dict, verbose_name='Данные о задачах')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='ReportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_before', models.CharField(max_length=50, verbose_name='Статус до')),
                ('status_after', models.CharField(blank=True, max_length=50, verbose_name='Статус после')),
                ('time_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Затрачено часов')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_tasks', to='reports.report', verbose_name='Отчет')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_tasks', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Задача в отчете',
                'verbose_name_plural': 'Задачи в отчетах',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('frequency', models.CharField(choices=[('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('quarterly', 'Ежеквартально'), ('manual', 'По требованию')], default='weekly', max_length=20, verbose_name='Периодичность')),
                ('deadline_days', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Дней на заполнение')),
                ('questions', models.JSONField(default=list, help_text='Список вопросов в формате: [{"id": "q1", "label": "Вопрос", "type": "text/select/date"}]', verbose_name='Вопросы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Шаблон отчета',
                'verbose_name_plural': 'Шаблоны отчетов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.reporttemplate', verbose_name='Шаблон'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('template', 'user', 'period_start', 'period_end')},
        ),
    ]
