# Generated by Django 5.2.12 on 2026-05-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='questions',
        ),
        migrations.AddField(
            model_name='report',
            name='submitted_file',
            field=models.FileField(blank=True, upload_to='report_submissions/%Y/%m/', verbose_name='Загруженный отчет (.docx)'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='template_file',
            field=models.FileField(blank=True, upload_to='report_templates/%Y/%m/', verbose_name='Файл шаблона (.docx)'),
        ),
    ]
