# Generated by Django 5.2.12 on 2026-03-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_priority_task_technical_spec_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskattachment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Вложение задачи', 'verbose_name_plural': 'Вложения задач'},
        ),
        migrations.RenameField(
            model_name='taskattachment',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='attachment_type',
            field=models.CharField(choices=[('file', 'Файл'), ('link', 'Ссылка')], default='file', max_length=10, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='url',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
