# Generated by Django 5.2.12 on 2026-05-15 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1024, verbose_name='Название')),
                ('authors', models.JSONField(blank=True, default=list, verbose_name='Авторы')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('journal', models.CharField(blank=True, max_length=512, verbose_name='Журнал / источник')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='Том')),
                ('issue', models.CharField(blank=True, max_length=50, verbose_name='Выпуск')),
                ('pages', models.CharField(blank=True, max_length=50, verbose_name='Страницы')),
                ('url', models.URLField(blank=True, max_length=2048, verbose_name='URL')),
                ('doi', models.CharField(blank=True, max_length=255, verbose_name='DOI')),
                ('raw_url', models.URLField(blank=True, max_length=2048, verbose_name='Исходный URL')),
                ('gost_string', models.TextField(blank=True, verbose_name='ГОСТ-строка')),
                ('extraction_confidence', models.CharField(blank=True, choices=[('high', 'Высокая'), ('medium', 'Средняя'), ('low', 'Низкая')], default='low', max_length=10, verbose_name='Уверенность извлечения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-created_at'],
            },
        ),
    ]
